In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_regression

x,y=make_regression(
    n_samples=1000,
    n_features=2,
    random_state=42
)

In [3]:
x

array([[ 0.43004165,  0.38193545],
       [ 1.5615112 ,  1.30174129],
       [-0.56629773, -0.99053633],
       ...,
       [ 1.7722516 , -0.02751491],
       [ 0.56390912,  1.38427282],
       [ 1.69645637, -2.08192941]])

In [4]:
y

array([ 1.83875383e+01,  6.33022437e+01, -4.40634991e+01, -2.62237930e+01,
        1.18159607e+01,  8.39158760e+00, -1.70514801e+01, -4.11884511e+01,
        6.62642407e+00,  3.44518522e+01, -1.55969123e+01,  3.63972034e+01,
       -2.29579700e+00,  5.89310496e+01, -4.77572478e+01,  2.67855723e+00,
       -1.95950711e+01,  5.49363192e+01,  2.51002061e+01, -5.34154264e+00,
        1.03080357e+01, -5.89970937e+01, -6.88666498e+01,  9.77318499e+01,
       -5.95309054e+01,  3.78311665e+01,  3.88723141e+01,  2.25707029e+00,
       -6.82430997e+01, -3.27733603e+01, -2.39501404e-01,  5.74157173e+00,
        2.95560217e+01,  1.49492582e+01,  8.72032067e+00, -2.97035883e+01,
       -7.34638694e+01, -8.47551895e+01,  8.28675690e+01, -2.03970724e+01,
        2.98462180e+01,  6.53238200e+01,  2.80492162e+01,  3.51427408e+01,
        3.50781476e+00, -1.18418761e+01, -4.50843833e-01,  2.89939869e+01,
        8.33925485e+01, -4.65078736e+01,  4.28510406e+00,  2.54742902e+01,
       -8.86921754e-01,  

In [5]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [6]:
from sklearn.neighbors import KNeighborsRegressor

knn=KNeighborsRegressor()

knn.fit(x_train,y_train)

KNeighborsRegressor()

In [7]:
y_pred=knn.predict(x_test)
y_pred

array([-5.54883566e+00, -1.93629465e+01,  3.19688872e+01,  6.82552863e+01,
       -3.81963471e+01,  7.58483233e+01,  7.08679794e-01,  4.59777566e+01,
        3.60118212e+01, -5.65770895e+00,  2.52449720e+01, -2.48362645e+01,
       -2.09314784e+01, -4.96166748e+00,  5.50211656e+01, -9.79823312e-02,
        7.08679794e-01, -6.94101149e+01, -6.11229142e+01,  5.99587543e+01,
        6.19426460e+01,  7.87902498e+00, -7.61664924e+01,  3.16359112e+01,
        4.09535650e+01, -1.85148740e+01,  2.13081112e+01,  9.28910483e+01,
       -4.16387625e+00, -3.14488444e+01, -2.51414725e+01,  1.16226713e+01,
       -1.15112037e+01,  1.28282938e+00, -6.56792604e-01,  2.10469715e+01,
        9.65178747e+01, -3.16893062e+01,  2.76736228e+01,  2.21262731e+01,
        3.16782330e+01,  2.47785423e+01,  3.62460015e+01,  6.11613664e+01,
        2.15469101e+01,  5.00440511e+01,  2.87535165e+01,  1.81627321e+00,
        1.09297489e+01,  3.49072503e+01,  1.82566804e+00, -1.68404581e+01,
       -3.20784048e+01, -

In [8]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

7.852550632274679
1.8616067318727196
0.9949412980226552
