In [ ]:
# Logistic regression
# Our aim is to solve classig=fication problem.

# In precision, false positive is important.
# In Recall, false neagtive is important.

# Balanced dataset= accuracy
# Imbalanced dataset= precision

In [1]:
from sklearn.datasets import load_iris

In [16]:
ds=load_iris()
ds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
print(ds.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [4]:
ds.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
ds.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [19]:
# Coverting dataset into dataframe.

df=pd.DataFrame(ds.data,columns=ds.feature_names)

In [20]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [21]:
df["target"]=ds.target

In [22]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [23]:
ds.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
# Binary Classification

df["target"]!=2

0       True
1       True
2       True
3       True
4       True
       ...  
145    False
146    False
147    False
148    False
149    False
Name: target, Length: 150, dtype: bool

In [25]:
df_copy=df[df["target"]!=2]

In [26]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [27]:
df_copy.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
95       1  
96       1  
97       1  
98       1  
99       1

In [29]:
# Dependent and independent features.

x=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [30]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [31]:
from sklearn.linear_model import LogisticRegression

lg=LogisticRegression()

In [32]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

In [33]:
# Fitting data

lg.fit(x_train,y_train)

LogisticRegression()

In [34]:
# Prediction

y_pred=lg.predict(x_test)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [35]:
lg.predict_proba(x_test)

array([[0.94955828, 0.05044172],
       [0.97446425, 0.02553575],
       [0.01575126, 0.98424874],
       [0.98330496, 0.01669504],
       [0.00413098, 0.99586902],
       [0.93901825, 0.06098175],
       [0.01552513, 0.98447487],
       [0.01041804, 0.98958196],
       [0.9569719 , 0.0430281 ],
       [0.97668395, 0.02331605],
       [0.9541689 , 0.0458311 ],
       [0.98045049, 0.01954951],
       [0.01881423, 0.98118577],
       [0.95813469, 0.04186531],
       [0.98819936, 0.01180064],
       [0.98310048, 0.01689952],
       [0.98798019, 0.01201981],
       [0.96287265, 0.03712735],
       [0.98228589, 0.01771411],
       [0.00366505, 0.99633495]])

In [36]:
# Calculating metrics

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [37]:
print(confusion_matrix(y_test,y_pred))

[[14  0]
 [ 0  6]]


In [38]:
print(accuracy_score(y_test,y_pred))

1.0


In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         6

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [42]:
# hyperparameter tuning

#GridSearchCV

from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

parameters = {'penalty':['l1','l2','elasticnet',None],
              'C' : [1,10,20,30],
              'max_iter' : [100, 200, 300]
              }

clf = GridSearchCV(lg, param_grid = parameters)

In [43]:
# Splitting of train data to validation data
clf.fit(x_train, y_train)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30], 'max_iter': [100, 200, 300],
                         'penalty': ['l1', 'l2', 'elasticnet', None]})

In [44]:
clf.best_params_

{'C': 1, 'max_iter': 100, 'penalty': 'l2'}

In [45]:
classifier = LogisticRegression(C = 1, penalty = 'l2',max_iter = 100)

In [46]:
classifier.fit(x_train,y_train)

LogisticRegression(C=1)

In [47]:
# Prediction

y_pred = classifier.predict(x_test)

print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[14  0]
 [ 0  6]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         6

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [48]:
# RandomizedSearchCV

from sklearn.model_selection import RandomizedSearchCV

random_clf = RandomizedSearchCV(LogisticRegression(), param_distributions=parameters)

random_clf.fit(x_train,y_train)

random_clf.best_params_

classifier = LogisticRegression(C = 10, penalty = None, max_iter = 100)

classifier.fit(x_train, y_train)

## Prediction
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))


[[14  0]
 [ 0  6]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         6

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [ ]:
# Import pickle for saving and loading the model

import pickle

# Filepath for saving the model
pickle_file_path = 'logistic.pkl'

# Save the trained model to a pickle file
with open(pickle_file_path, 'wb') as file:
    pickle.dump(classifier, file)

print(f'Model saved to {pickle_file_path}')

# Load the model from the pickle file
with open(pickle_file_path, 'rb') as file:
    loaded_model = pickle.load(file)

# Test the loaded model with predictions
y_pred_loaded = loaded_model.predict(x_test)
print(y_pred_loaded)